"""Regenerate index.md — the browsable table of contents for the book repository.

The printed book gets its table of contents from render.py at render time.
index.md is the GitHub-facing equivalent: the same entries in the same book
order, as links you can click without building anything.

Hand-maintaining it does not work — links drift as entries are renamed — so it
is generated from the book/ tree and regenerated whenever entries are added,
renamed, or removed.

Usage:
    cookbook index           # rewrite index.md
    cookbook index --check   # exit 1 if index.md is stale (CI)
"""
from __future__ import annotations

import sys
from pathlib import Path

from . import render

ROOT = render.ROOT
OUTPUT = ROOT / "index.md"

HEADER = """<!-- Generated by `cookbook index` — do not edit by hand. -->
# {title}

Every entry in the book, in book order. `cookbook press` produces the printed
edition.

Each entry links to its clean text, its verbatim transcription when one exists,
and its photo when one exists.
"""


def link(label: str, path: Path) -> str:
    return f"[{label}]({path.relative_to(ROOT).as_posix()})"


def build() -> str:
    # Dividers and generated pages (title, contents, contributors, index) are
    # book furniture with no files to link, not entries.
    recipes = [r for r in render.assemble_recipes() if not (r.is_divider or r.is_generated)]
    out = [HEADER.format(title=render.CONFIG.title)]
    current = None

    for r in recipes:
        if r.category != current:
            current = r.category
            out.append(f"\n## {render.CATEGORY_LABELS.get(r.category, r.category)}\n")

        folder = r.folder
        parts = [link("text", folder / r.md_filename)]

        original = folder / "sources" / r.original_filename
        if original.exists():
            parts.append(link("original", original))

        photo = folder / "images" / f"{r.slug}.jpg"
        if photo.exists():
            parts.append(link("photo", photo))

        title = r.title or r.slug
        attribution = f" — *{r.attribution}*" if r.attribution else ""
        out.append(f"- **{title}**{attribution}: {', '.join(parts)}")

    photos = sum(1 for r in recipes if (r.folder / "images" / f"{r.slug}.jpg").exists())
    out.append(f"\n---\n\n{len(recipes)} entries, {photos} with photographs.\n")
    return "\n".join(out)


def main(check: bool = False) -> int:
    text = build()

    if check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != text:
            print("index.md is stale — run: cookbook index", file=sys.stderr)
            return 1
        print("index.md is up to date")
        return 0

    OUTPUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0
